export * from './product-album'
export * from './product-specification'
export * from './socialMedia-share'
export * from './productTexts/productDescription'
export * from './rating-card'
export * from './rating'
export *  from './tab'
export *  from './breadcrumb'